namespace Recrutador.SignalR.Contracts;

/// <summary>
///     A single STT-shaped final segment generated by the simulation backend.
///     The HUD plays these back through the existing transcript pipeline as if
///     they were emitted by the real STT provider.
/// </summary>
/// <param name="Speaker">Either "Interviewer" or "Candidate".</param>
/// <param name="Content">Transcribed-style spoken text (digits as digits, fillers, etc.).</param>
public sealed record SimulatedChunkContract(
    string Speaker,
    string Content);
