namespace Recrutador.SignalR.Contracts;

/// <summary>
///     Anchor data describing the simulated candidate's identity and background.
///     Generated by the backend on the first turn of a session and round-tripped by
///     the HUD on every subsequent turn so consistency holds across level changes.
/// </summary>
/// <param name="DisplayName">Short display name (e.g. "Tatiane").</param>
/// <param name="OneLineBackground">One-line summary tying the candidate to the role.</param>
/// <param name="ClaimedExperiences">3-5 short anchors the LLM must respect across turns.</param>
/// <param name="SpeakingStyle">Voice and register cues for the spoken-STT rendering.</param>
public sealed record SimulatedPersonaContract(
    string DisplayName,
    string OneLineBackground,
    IReadOnlyList<string> ClaimedExperiences,
    string SpeakingStyle);
